server:
  port: ${SERVER_PORT:8701}
  
eureka:
  client:
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

spring:
  rabbitmq:
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: transaction-queue